# Typology rhythm automation tutorial by Yan

## Made for Ling 199



*   Always thank your fellow linguists for completing the most important task, the transcription!
* (IN PRAAT) [OPTIONAL] What you can do is go to Text writing settings. In the Settings submenu of the Praat menu, and there set the output encoding to UTF-8. Praat will from then on save your text files in the UTF-8 format, which means one byte for every ASCII character and 2 to 4 bytes for every non-ASCII character. Especially on Linux, many programs understand UTF-8 text and will display the correct characters. Programs such as SPSS do not understand UTF-8 but will still display ASCII characters correctly; for instance, the names München and Wałęsa may appear as MÃ÷nchen and WaÅ,Ä™sa or so.
*   Make sure sheet does not have empty cells in obvious locations such as phoneme or word column.
*   For single-parsed sentences, remove empty rows before running the script.
*   Always check for any weird inconsistency to save yourself time.
* Report any new language nuances to Sherry, and consult with Yan on how to fix.

Clone the script to load it in for use, you should see it in the left menu after navigating to the folder with `cd`.

In [ ]:
!git clone https://github.com/YLashchev/IPA_parser.git

### Local usage (non-Colab)
If you already have this repo locally, skip the clone step and run the cell below instead.

In [1]:
%cd ..
!.venv/bin/python -m pip install -e .
!.venv/bin/python -m ipykernel install --user --name ipa-parser

/Users/yanlashchev/Desktop/IPA_Project/IPA_parser
Obtaining file:///Users/yanlashchev/Desktop/IPA_Project/IPA_parser
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: pandas>=2.2.0 in ./.venv/lib/python3.12/site-packages (from ipa-parser==0.1.0) (3.0.1)
Requirement already satisfied: openpyxl>=3.1.2 in ./.venv/lib/python3.12/site-packages (from ipa-parser==0.1.0) (3.1.5)
Requirement already satisfied: et-xmlfile in ./.venv/lib/python3.12/site-packages (from openpyxl>=3.1.2->ipa-parser==0.1.0) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas>=2.2.0->ipa-parser==0.1.0) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas>=2.2.0->ipa-parser==0.1.0) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->ipa-parser==0.1.0) (1.17.0)
Building wheels for collected packages: ipa-parser
  Building editable for ipa-parser (pyproject.toml) ... done
  Created wheel for ipa-parser: filename=ipa_parser-0.1.0-0.editable-py3-none-any.whl size=2311 sha256=4fba502fac7bc8274e90758fbf7727da35352a75f319f41e779b6cf9a0296aa4
  Stored in directory: /private/var/folders/kg/96f7zf8d0wxdsgdpg521tsr00000gr/T/pip-ephem-wheel-cache-kaf_xc5w/wheels/ff/ca/4b/ad7c4b294f776dda65f2893720394bcc5f88751c3c1b93d3a8
Successfully built ipa-parser
Installing collected packages: ipa-parser
  Attempting uninstall: ipa-parser
    Found existing installation: ipa-parser 0.1.0
    Uninstalling ipa-parser-0.1.0:
      Successfully uninstalled ipa-parser-0.1.0
Successfully installed ipa-parser-0.1.0
Installed kernelspec ipa-parser in /Users/yanlashchev/Library/Jupyter/kernels/ipa-parser

In [2]:
!.venv/bin/python -c "import sys; print(sys.executable)"
!.venv/bin/python -c "import IPA; print(IPA.__file__)"

/Users/yanlashchev/Desktop/IPA_Project/IPA_parser/.venv/bin/python
/Users/yanlashchev/Desktop/IPA_Project/IPA_parser/src/IPA/__init__.py

In [3]:
%cd IPA

[Errno 2] No such file or directory: 'IPA'
/Users/yanlashchev/Desktop/IPA_Project/IPA_parser

In [ ]:
%cd IPA_parser
!pip install -e .

### Import custom classes from scripts and Pandas to work with DataFrame structure.

In [4]:
from IPA import CustomCharacter, IPA_CHAR, IPAString
import pandas as pd
import numpy as np

# Pre-processing

## Configure language settings



*  Set `GEMINATE` value to True/False if present, or define custom geminates if not.
*   clear previously defined custom characters if any (to be safe).
*   Add custom characters using `CustomCharacter` class for all affricates/diphtongs. Otherwise count will be wrong.
*   For now set affricate to 'CONSONANT', Diphtong to 'VOWEL' with rank = 1.

In [5]:
GEMINATE = False
CustomCharacter.clear_all_chars()
CustomCharacter.add_char('OP', 'PAUSE', rank = 0)
CustomCharacter.add_char('SP', 'PAUSE', rank = 0)
CustomCharacter.add_char('ʁ', 'CONSONANT', rank = 1)
CustomCharacter.add_char('t͡s', 'CONSONANT', rank = 1)




#ZwaraBerber

In [ ]:
GEMINATE = True


CustomCharacter.clear_all_chars()



CustomCharacter.add_char('OP', 'PAUSE', rank = 0)
CustomCharacter.add_char('SP', 'PAUSE', rank = 0)
CustomCharacter.add_char('sˁ', 'CONSONANT',rank=1)
CustomCharacter.add_char('nˁ', 'CONSONANT',rank=1)
CustomCharacter.add_char('dˁ', 'CONSONANT',rank=1)
CustomCharacter.add_char('lˁ', 'CONSONANT',rank=1)
CustomCharacter.add_char('mˁ', 'CONSONANT',rank=1)
CustomCharacter.add_char('rˁ', 'CONSONANT',rank=1)
CustomCharacter.add_char('nˁnˁ', 'CONSONANT',rank=1)
CustomCharacter.add_char('mˁmˁ', 'CONSONANT',rank=1)

# Northwest Sahaptin

In [5]:
GEMINATE = False

CustomCharacter.clear_all_chars()
CustomCharacter.add_char('OP', 'PAUSE', rank = 0)
CustomCharacter.add_char('SP', 'PAUSE', rank = 0)
CustomCharacter.add_char('t͡s', 'CONSONANT',rank=1)
CustomCharacter.add_char('t͡s’', 'CONSONANT',rank=1)
CustomCharacter.add_char('t͡ʃ’', 'CONSONANT',rank=1)
CustomCharacter.add_char('t͡ʃ', 'CONSONANT',rank=1)
CustomCharacter.add_char('q’', 'CONSONANT',rank=1)

# Oriental Hebrew

In [ ]:
GEMINATE = False

CustomCharacter.clear_all_chars()

CustomCharacter.add_char('OP', 'PAUSE', rank = 0)
CustomCharacter.add_char('SP', 'PAUSE', rank = 0)
CustomCharacter.add_char('t͡s', 'CONSONANT',rank=1)
CustomCharacter.add_char('ts', 'CONSONANT',rank=1)

In [ ]:
GEMINATE = False
CustomCharacter.add_char('ᵐ̥p', 'CONSONANT',rank=1)
CustomCharacter.add_char('ᵐ', 'CONSONANT',rank=0)
CustomCharacter.add_char('ᵐ̥', 'CONSONANT',rank=0)
CustomCharacter.add_char('ʈ͡ʂ', 'CONSONANT',rank=1)
CustomCharacter.add_char('ɖ͡ʐ', 'CONSONANT',rank=1)
CustomCharacter.add_char('t͡sʲ', 'CONSONANT',rank=1)
CustomCharacter.add_char('ʈ̬͡ʂ̬', 'CONSONANT',rank=1)

#ʈ͡ʂ
#ʈ̬͡ʂ̬
#ɖ͡ʐ
#t͡sʲ

#ᵐ̥p
#ᵐ

## Load the data in

* You can drag the excel sheet into the menu in the right then (right-click copy path) and enter it into the input.
* We then fix the original columns names to be safe.
* Copy path from sheets to use as example.

In [6]:
#file_path = input("Enter the path to your Excel file: ")
#/content/IPA_parser/data/sheets/NorthernTepehuan.xlsx
#/content/IPA_parser/data/sheets/NorthwestSahaptin.xlsx



# Read the Excel file using the provided path
df = pd.read_excel('/Users/yanlashchev/Desktop/IPA_Project/IPA_parser/data/sheets/Sheets/NorthwestSahaptin.xlsx', engine='openpyxl')

# Correct original columns names to be safe
new_columns = ['Filename', 'Sentence', 'Word', 'Phoneme', 'Begin', 'End', 'Duration (ms.)']
df.columns = new_columns

In [7]:
df

,Filename,Sentence,Word,Phoneme,Begin,End,Duration (ms.)
0,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,ʔ,0.08876,0.12333,34.57
1,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,a,0.12333,0.26802,144.69
2,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,t,0.26802,0.45239,184.38
3,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,j,0.45239,0.50462,52.23
4,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,a,0.50462,0.64145,136.83
...,...,...,...,...,...,...,...
385,09-Cold_Wind_and_Sun-9_of_9,S9,ˈχtut.χaw,u,6.36828,6.47982,111.54
386,09-Cold_Wind_and_Sun-9_of_9,S9,ˈχtut.χaw,t,6.47982,6.55789,78.07
387,09-Cold_Wind_and_Sun-9_of_9,S9,ˈχtut.χaw,χ,6.55789,6.70504,147.15
388,09-Cold_Wind_and_Sun-9_of_9,S9,ˈχtut.χaw,a,6.70504,6.80879,103.76
389,09-Cold_Wind_and_Sun-9_of_9,S9,ˈχtut.χaw,w,6.80879,6.93028,121.49

### Helper functions `inset_sp(df)` and `assign_pauses`

`insert_sp(df)` does a couple things:

1.   Adds 'SP' to Sentence column (for verification purposes and my sanity)
2.   If there is no empty cell between sentences but there is a transition add a row. (This is for single-sentence parsed transcriptions). This is why removing the empty rows is important pre-processing. We do not want to mistake a NaN value for an empty row. Luckily the data is always short enough to visibly check.
3. For the SP added to the single-sentence parsed transcriptions we put duration of 0, and handle this case appropriately below when neccessary.

`assign_pauses`
* puts 'OP' and 'SP' into the respective word and phoneme columns for sanity check.

In [8]:
def insert_sp(df):
    # Check if 'SP' already exists in the 'Phoneme' column
    if 'SP' in df['Phoneme'].values:
        return df  # Return the original DataFrame if 'SP' already exists

    rows = []
    for i in range(len(df) - 1):
        current_row = df.iloc[i]
        next_row = df.iloc[i + 1]

        # Add the current row to the new list
        rows.append(current_row)

        # Check for sentence transition
        if current_row['Sentence'] != next_row['Sentence']:
            # Insert 'SP' row
            sp_row = current_row.copy()
            sp_row[:] = 'SP'  # Set all values to 'SP'
            sp_row['Sentence'] = 'SP'
            sp_row['Duration (ms.)'] = 0
            rows.append(sp_row)

    # Add the last row of the original dataframe
    rows.append(df.iloc[-1])

    return pd.DataFrame(rows).reset_index(drop=True)





def assign_pauses(dataframe, phoneme_column='Phoneme', word_column='Word'):
    # Iterate through the DataFrame
    for i in dataframe.index:
        # Check if the current phoneme is 'OP' or 'SP'
        if dataframe.at[i, phoneme_column] in ['OP', 'SP']:
            # Assign it to the 'Word' column
            dataframe.at[i, word_column] = dataframe.at[i, phoneme_column]

In [9]:
df = insert_sp(df)
assign_pauses(df)



def is_double_consonant(phoneme):
    clean_phoneme = IPAString(phoneme,geminate=GEMINATE).char_only()
    return len(phoneme) == 2 and IPAString(clean_phoneme).segment_type == ['CONSONANT']

# Initialize an empty list to store the indices
double_consonant_indices = []

# Iterate through the DataFrame's 'Phoneme' column
for i in range(1, len(df['Phoneme'])):
    # Check if the current and previous phonemes are both double consonants
    if is_double_consonant(df['Phoneme'].iat[i]) and df['Phoneme'].iat[i] == df['Phoneme'].iat[i-1]:
        double_consonant_indices.append(i-1)


# The result is a list of indices of the DataFrame where the double consonants occur

for i in double_consonant_indices:
  print(i, df.iloc[i]['Phoneme'])

138 χʷ

### Word Level

* Get original word list by first appearace (i.e., non-repeat) and index of occurence.

* Logic is simple, if next word is the same as previous word still the same word.

***NOTE***: This will be an issue if there is a language where the word is repeated twice on purpose. "The food was **so so**"

In [10]:
def get_word_list_and_indices(df, word_column='Word'):
    if df.empty:
        return [], []

    unique_words = []
    indices = []
    last_word = None

    for idx, row in df.iterrows():
        word = row[word_column]
        if word != last_word:
            unique_words.append(word)
            indices.append(idx)
            last_word = word

    return unique_words, indices

In [11]:
unique_words, indices = get_word_list_and_indices(df)

def find_non_string_index(words,indices):
    for word, index in zip(words,indices):
        if not isinstance(word, str):
            return index +2
    return None

print(find_non_string_index(unique_words,indices))

print(f'Like original transcription\n{unique_words}')
print(f'The index of the word in Dataframe\n{indices}')

None
Like original transcription
['ʔa.tja.ˈjaː.ja', 'ˈʔaː.nin', 'SP', 'pa.pa.ta.na.ˈwiːχ.ʃa.na', 'ʔa.tja.ˈjaː.ja ', 'ˈʔaː.nin', 'OP', 'ˈʃin', 'ʔi.ˈwa', 'ˈχtut.χaw', 'SP', 'ˈkuːk', 'awˈku ', 'ʔi.ˈpaj.ʃna', 'ˈt͡smuj', 'ˈʔut.paː.sji', 'wja.ninˈ.ɬa', 'SP', 'ˈpa.pa.ʔiː.ʔiː.na', 'ʔa.tja.ˈjaː.ja ', 'ˈʔaː.nin', 'ʔa.na.ˈpɨn.χuʃ', 'ʔi.ʃa.ˈpa.t͡ʃaχʷt͡ʃ.kta', 'ˈʔut.paːs', 'wja.nin.ˈɬaːn', 'ʔi.ˈwa.ta', 'ˈχtut.χaw', 'SP', 'ʔaw.ˈku', 'ʔa.tja.ˈjaː.ja ', 'ʔiws.ˈla.t͡saj.ka', 'ˈχtu.wi.ki', 'ku.tja', 'ʔa.na.ˈmɨɬ', 'ʔi.ˈhu.li.na', 'ku', 'majk.ˈqaːp', 'pi.ˈna.t͡ʃat͡s.muj.ka', 'wja.nin.ˈɬa', 'SP', 'ku', 'awˈku ', 'pi.ˈna.jaːn.wa.na', 'ʔa.tja.ˈjaː.ja ', 'SP', 'ku', 'a.na.ˈmaːl', 'ˈʔaːn', 'ʔi.ˈχtu.na', 'ʔi.ʔɨ.ˈt͡ʃu.na', 'SP', 'ˈkuːk', 'awˈku', 'ʔi.ˈla.χuj.χna', 'wja.nin.ˈɬa', 'ku', 'i.ˈt͡ʃaχʷ.t͡ʃka', 'ˈʔut.paːs', 'SP', 'ku ', 'awˈku', 'pi.ˈna.jaːn.wa.na', 'ʔa.tja.ˈjaː.ja ', 'ˈʔaw', 'ˈʔin.χaj', 'ˈʔaːn', 'ʔi.ˈwa', 'ˈχtut.χaw']
The index of the word in Dataframe
[0, 9, 14, 15, 30, 39, 44, 45, 48, 52, 59, 60, 63, 67, 75, 79, 87, 95, 96, 106, 115, 120, 130, 143, 149, 158, 164, 171, 172, 177, 186, 197, 204, 209, 216, 224, 226, 233, 245, 253, 254, 256, 260, 271, 280, 281, 283, 289, 292, 299, 307, 308, 311, 315, 325, 333, 335, 342, 348, 349, 351, 355, 366, 375, 378, 384, 387, 391]

`find_mismatches_with_phoneme_alignment`
* loops through each word and compare the concatenated phoneme with the word itself. If there is a mismatch, we add the word index and the word itself to a list. We return the list of mismatches.
* Sometimes mismatch is due to diff characters with same representation like small cap latin letters which just requires a simple replacement.

In [12]:
def find_mismatches_with_phoneme_alignment(df, original_word_list, word_start_indices, phoneme_column='Phoneme'):
    mismatches = []
    num_words = len(original_word_list)

    for i in range(num_words):
        word = original_word_list[i]
        start_idx = word_start_indices[i]
        end_idx = word_start_indices[i + 1] if i + 1 < num_words else len(df)


        # Concatenate phonemes for the current word
        concatenated_phoneme = ''.join([IPAString(df.at[idx, phoneme_column].strip(),geminate=False).char_only() for idx in range(start_idx, end_idx)])

        # Check for a mismatch
        if IPAString(word.strip()).char_only() != concatenated_phoneme:
            mismatches.append((start_idx+2, word))

    return mismatches



mismatches = find_mismatches_with_phoneme_alignment(df, unique_words, indices)

print(mismatches)

[(132, 'ʔi.ʃa.ˈpa.t͡ʃaχʷt͡ʃ.kta')]

#### Helper function and Word Columns


*   `collapse_nested_list` does what it says, takes a nested list of lists and makes it one vector.
*   `word_columns`

  1.  Iterates unique words getting phonological length based on custom script
  2.  repeats this word by the phonological length alongside the **Word Number** in sentence.
  3. reset at occurence of SP.
  4. returns the repeated word list, the word labels (Word Number column), and the unique index for every word.


* `process_durations`
  * gets duration based on unique index list.

In [13]:
# function to collapse nested lists of lists into one list
def collapse_nested_list(nested_list) -> list:
    collapsed = []
    for item in nested_list:
        if isinstance(item, list):
            collapsed.extend(item)
        else:
            collapsed.append(item)

    return collapsed



#function to create word columns
def word_columns(original_word_list):
    j = 1  # Unique index counter
    repeated_word_list = []
    word_labels = []
    unique_idx = []
    i = 1  # Word label counter
    for word in original_word_list:
        if word == 'OP':
            # Append 'OP' without affecting the counter's increment
            repeated_word_list.append(word)
            word_labels.append(word)  # Use the current i value but do not increment it
            unique_idx.append(word)
        elif word == 'SP':
            # For 'SP', reset i to 0 after appending
            repeated_word_list.append(word)
            word_labels.append(word)
            unique_idx.append(word)
            i = 1  # Reset i for word labels after 'SP'
        else:
            # Calculate phonological length and append word, labels, and indexes
            phonological_length = IPAString(word,geminate=False).total_length()
            repeated_word_list.append([word] * phonological_length)
            word_labels.append([i] * phonological_length)
            unique_idx.append([j] * phonological_length)
            i += 1  # Only increment i for normal words
        j += 1  # Increment j for each word, including 'OP' and 'SP'

    # Flatten the nested lists
    repeated_word_list = collapse_nested_list(repeated_word_list)
    word_labels = collapse_nested_list(word_labels)
    unique_idx = collapse_nested_list(unique_idx)

    return repeated_word_list, word_labels, unique_idx

def process_durations(df,unique_word_idx):
    durations_output = []

    current_word = None
    current_sum = 0

    for _, row in df.iterrows():
        idx_number = row[unique_word_idx]
        duration = row['Duration (ms.)']

        # Directly append for OP or SP
        if idx_number == "OP" or idx_number == "SP":
            if current_word is not None:
                durations_output.extend([current_sum] * current_count)
                current_word = None
                current_sum = 0
                current_count = 0
            durations_output.append(duration)
            continue

        # Summing logic
        if current_word == idx_number:
            current_sum += duration
            current_count += 1
        else:
            if current_word is not None:
                durations_output.extend([current_sum] * current_count)
            current_word = idx_number
            current_sum = duration
            current_count = 1

    # Add the durations for the last word
    if current_word is not None:
        durations_output.extend([current_sum] * current_count)

    return durations_output

checking lengths match.

In [14]:
repeated_word_list, word_labels, unique_word_idx = word_columns(unique_words)
print('original word column',len(df['Word']))# original length
print('repeated_word_list',len(repeated_word_list))
print('word_labels',len(word_labels))
print('unique_word_idx',len(unique_word_idx))


print(f'\nthe repeated words {repeated_word_list[:17]}\n')
print(f'the unique id corresponding to each word {unique_word_idx[:17]}')

original word column 398
repeated_word_list 398
word_labels 398
unique_word_idx 398

the repeated words ['ʔa.tja.ˈjaː.ja', 'ʔa.tja.ˈjaː.ja', 'ʔa.tja.ˈjaː.ja', 'ʔa.tja.ˈjaː.ja', 'ʔa.tja.ˈjaː.ja', 'ʔa.tja.ˈjaː.ja', 'ʔa.tja.ˈjaː.ja', 'ʔa.tja.ˈjaː.ja', 'ʔa.tja.ˈjaː.ja', 'ˈʔaː.nin', 'ˈʔaː.nin', 'ˈʔaː.nin', 'ˈʔaː.nin', 'ˈʔaː.nin', 'SP', 'pa.pa.ta.na.ˈwiːχ.ʃa.na', 'pa.pa.ta.na.ˈwiːχ.ʃa.na']

the unique id corresponding to each word [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 'SP', 4, 4]

`Word_Length_By_Phoneme`


*   Creats WordLengthByPhoneme Column by using `total_length()` from `IPAString`.
*   Appends OP and SP as they were.

`Word_Length_By_Syllable`


*   Creats WordLengthBySyllable Column by using `syllables` from `IPAString`.
*   Appends OP and SP as they were.

In [15]:
#function to label word length by phoneme
def Word_Length_By_Phoneme(repeated_word_list):
    wlbp = []
    for word in repeated_word_list:
        if word == 'OP' or word == 'SP':
            wlbp.append(word)
        else:
            wlbp.append(IPAString(IPAString(word,geminate=GEMINATE).char_only()).total_length())
            #print(word, IPAString(word).total_length())
    return wlbp


#function to label word length by syllable
def Word_Length_By_Syllable(repeated_word_list):
    wlbs = []
    for word in repeated_word_list:
        if word == 'OP' or word == 'SP':
            wlbs.append(word)
        else:
            wlbs.append(len(IPAString(word).syllables))
    return wlbs

In [16]:
wlbp = Word_Length_By_Phoneme(repeated_word_list)
wlbs = Word_Length_By_Syllable(repeated_word_list)
print('wlbp',len(wlbp))
print('wlbs',len(wlbs))

wlbp 398
wlbs 398

## Partial Sheet Check

I line up the original word data with the repeated words based on phonological length. I check the sheet 'check.xlsx' in the menu and see where the misalignment happens, and then either fix the missing character or add the custom character to the list above.

### Rinse & Refresh.

In [17]:
data = {
    'Original Word Column': df['Word'],
    'Repeated Word List': repeated_word_list,
    'Word Labels': word_labels,
    'Unique Word Index': unique_word_idx,
    'Phoneme': df['Phoneme'],
    'wlbp': wlbp,
    'wlbs': wlbs
}

# Converting the dictionary into a DataFrame
test_df = pd.DataFrame({k: pd.Series(v) for k, v in data.items()})



test_df.to_excel("check.xlsx")

In [18]:
#Keep columns
df['WordLengthByPhoneme'] = wlbp
df['WordLengthBySyllable'] = wlbs
df['WordNumber'] = word_labels

#temporary
df['unique_word_idx'] = unique_word_idx

print(df)

#use temporary for durations
summed_word_durations = process_durations(df,'unique_word_idx')
df['WordDuration'] = summed_word_durations

                        Filename Sentence            Word Phoneme    Begin  \
0    01-Cold_Wind_and_Sun-1_of_9       S1  ʔa.tja.ˈjaː.ja       ʔ  0.08876
1    01-Cold_Wind_and_Sun-1_of_9       S1  ʔa.tja.ˈjaː.ja       a  0.12333
2    01-Cold_Wind_and_Sun-1_of_9       S1  ʔa.tja.ˈjaː.ja       t  0.26802
3    01-Cold_Wind_and_Sun-1_of_9       S1  ʔa.tja.ˈjaː.ja       j  0.45239
4    01-Cold_Wind_and_Sun-1_of_9       S1  ʔa.tja.ˈjaː.ja       a  0.50462
..                           ...      ...             ...     ...      ...
393  09-Cold_Wind_and_Sun-9_of_9       S9       ˈχtut.χaw       u  6.36828
394  09-Cold_Wind_and_Sun-9_of_9       S9       ˈχtut.χaw       t  6.47982
395  09-Cold_Wind_and_Sun-9_of_9       S9       ˈχtut.χaw       χ  6.55789
396  09-Cold_Wind_and_Sun-9_of_9       S9       ˈχtut.χaw       a  6.70504
397  09-Cold_Wind_and_Sun-9_of_9       S9       ˈχtut.χaw       w  6.80879

         End  Duration (ms.) WordLengthByPhoneme WordLengthBySyllable  \
0    0.12333           34.57                   9                    4
1    0.26802          144.69                   9                    4
2    0.45239          184.38                   9                    4
3    0.50462           52.23                   9                    4
4    0.64145          136.83                   9                    4
..       ...             ...                 ...                  ...
393  6.47982          111.54                   7                    2
394  6.55789           78.07                   7                    2
395  6.70504          147.15                   7                    2
396  6.80879          103.76                   7                    2
397  6.93028          121.49                   7                    2

    WordNumber unique_word_idx
0            1               1
1            1               1
2            1               1
3            1               1
4            1               1
..         ...             ...
393          9              68
394          9              68
395          9              68
396          9              68
397          9              68

[398 rows x 11 columns]

### Syllable Level

`pre_syllable_columns`
* gets the list of syllables for each word using `.syllables` from `IPAString`.


`syllable_number`
* creates the SyllableNumber column by using the nested list and IPAString methods as before.

In [19]:
#function to create syllable columns
def pre_syllable_columns(unique_words) -> list:
    syllable_list = []

    for word in unique_words:
        if word == 'OP' or word == 'SP':
            syllable_list.append(word)
        else:
            syllables = IPAString(word, geminate=GEMINATE).syllables
            syllable_list.append(syllables)

    return syllable_list


# function to create syllable labels
def syllable_number(unique_syllables) -> list:
    syllable_labels = []

    for item in unique_syllables:
        # Check for 'OP' and 'SP' and add them directly
        if item == 'OP' or item == 'SP':
            syllable_labels.append(item)
            continue

        # For each syllable in the list item
        syllable_count = 1
        for syllable in item:
            phonological_length = IPAString(syllable,geminate=False).total_length()
            syllable_labels.extend([syllable_count] * phonological_length)
            syllable_count += 1

    return syllable_labels

Create syllable lists, SyllableNumber column, and placeholder columns

In [20]:
unique_syllables_nested = pre_syllable_columns(unique_words)
unique_syllables_flat = collapse_nested_list(unique_syllables_nested) #unique syllables
repeated_syllable_list,_,unique_syll_idx = word_columns(unique_syllables_flat) #apply repeat
syllable_labels = syllable_number(unique_syllables_nested) #apply numbering


#check length
print('syllable_labels',len(syllable_labels))
print('repeated_syllable_list',len(repeated_syllable_list))
print('unique_syll_idx',len(unique_syll_idx))

#Keep column
df['SyllableNumber'] = syllable_labels

#Temporary for later
df['syllables'] = repeated_syllable_list
df['unique_syll_idx'] = unique_syll_idx

df.head(25)

syllable_labels 398
repeated_syllable_list 398
unique_syll_idx 398

,Filename,Sentence,Word,Phoneme,Begin,End,Duration (ms.),WordLengthByPhoneme,WordLengthBySyllable,WordNumber,unique_word_idx,WordDuration,SyllableNumber,syllables,unique_syll_idx
0,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,ʔ,0.08876,0.12333,34.57,9,4,1,1,1187.84,1,ʔa,1
1,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,a,0.12333,0.26802,144.69,9,4,1,1,1187.84,1,ʔa,1
2,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,t,0.26802,0.45239,184.38,9,4,1,1,1187.84,2,tja,2
3,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,j,0.45239,0.50462,52.23,9,4,1,1,1187.84,2,tja,2
4,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,a,0.50462,0.64145,136.83,9,4,1,1,1187.84,2,tja,2
5,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,j,0.64145,0.74286,101.41,9,4,1,1,1187.84,3,ˈjaː,3
6,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,aː,0.74286,0.9927,249.84,9,4,1,1,1187.84,3,ˈjaː,3
7,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,j,0.9927,1.09994,107.24,9,4,1,1,1187.84,4,ja,4
8,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,a,1.09994,1.2766,176.65,9,4,1,1,1187.84,4,ja,4
9,01-Cold_Wind_and_Sun-1_of_9,S1,ˈʔaː.nin,ʔ,1.2766,1.38311,106.52,5,2,2,2,1062.23,1,ˈʔaː,5
10,01-Cold_Wind_and_Sun-1_of_9,S1,ˈʔaː.nin,aː,1.38311,1.67079,287.68,5,2,2,2,1062.23,1,ˈʔaː,5
11,01-Cold_Wind_and_Sun-1_of_9,S1,ˈʔaː.nin,n,1.67079,1.7844,113.61,5,2,2,2,1062.23,2,nin,6
12,01-Cold_Wind_and_Sun-1_of_9,S1,ˈʔaː.nin,i,1.7844,2.05116,266.75,5,2,2,2,1062.23,2,nin,6
13,01-Cold_Wind_and_Sun-1_of_9,S1,ˈʔaː.nin,n,2.05116,2.33883,287.67,5,2,2,2,1062.23,2,nin,6
14,SP,SP,SP,SP,SP,SP,0.00,SP,SP,SP,SP,0.00,SP,SP,SP
15,02-Cold_Wind_and_Sun-2_of_9,S2,pa.pa.ta.na.ˈwiːχ.ʃa.na,p,0.12928,0.15561,26.33,15,7,1,4,1717.09,1,pa,8
16,02-Cold_Wind_and_Sun-2_of_9,S2,pa.pa.ta.na.ˈwiːχ.ʃa.na,a,0.15561,0.26004,104.43,15,7,1,4,1717.09,1,pa,8
17,02-Cold_Wind_and_Sun-2_of_9,S2,pa.pa.ta.na.ˈwiːχ.ʃa.na,p,0.26004,0.322,61.97,15,7,1,4,1717.09,2,pa,9
18,02-Cold_Wind_and_Sun-2_of_9,S2,pa.pa.ta.na.ˈwiːχ.ʃa.na,a,0.322,0.43345,111.44,15,7,1,4,1717.09,2,pa,9
19,02-Cold_Wind_and_Sun-2_of_9,S2,pa.pa.ta.na.ˈwiːχ.ʃa.na,t,0.43345,0.53162,98.18,15,7,1,4,1717.09,3,ta,10
20,02-Cold_Wind_and_Sun-2_of_9,S2,pa.pa.ta.na.ˈwiːχ.ʃa.na,a,0.53162,0.66651,134.89,15,7,1,4,1717.09,3,ta,10
21,02-Cold_Wind_and_Sun-2_of_9,S2,pa.pa.ta.na.ˈwiːχ.ʃa.na,n,0.66651,0.74117,74.66,15,7,1,4,1717.09,4,na,11
22,02-Cold_Wind_and_Sun-2_of_9,S2,pa.pa.ta.na.ˈwiːχ.ʃa.na,a,0.74117,0.85921,118.03,15,7,1,4,1717.09,4,na,11
23,02-Cold_Wind_and_Sun-2_of_9,S2,pa.pa.ta.na.ˈwiːχ.ʃa.na,w,0.85921,0.96952,110.31,15,7,1,4,1717.09,5,ˈwiːχ,12
24,02-Cold_Wind_and_Sun-2_of_9,S2,pa.pa.ta.na.ˈwiːχ.ʃa.na,i,0.96952,1.1112,141.69,15,7,1,4,1717.09,5,ˈwiːχ,12

**SyllableLengthByPhoneme Column**
* use `.total_length()` from IPAString class on temporary syllable column

In [21]:
def Syllable_Length_By_Phoneme(repeated_syllable_list):
    slbp = []
    for syllable in repeated_syllable_list:
        if syllable == 'OP' or syllable == 'SP':
            slbp.append(syllable)
        else:
            slbp.append(IPAString(IPAString(syllable, geminate=GEMINATE).char_only()).total_length())
    return slbp

**SyllableLengthByPhoneme & SyllableDuration columns**

In [22]:
slbp = Syllable_Length_By_Phoneme(repeated_syllable_list)
summed_syll_durations = process_durations(df,'unique_syll_idx')
print('slbp',len(slbp))


#keep
df['SyllableLengthByPhoneme'] = slbp
df['SyllableDuration'] = summed_syll_durations

slbp 398

### Sentence level

`SentenceDUration`
1. We loop through every row in the dataframe, and get the index number of the word (e.g. 1, 2, 3, etc.). We also get the duration of the word.
2. If the index number is "OP" or "SP", we directly append the duration to the output list.
3. If the index number is not "OP" or "SP", we need to sum up the durations of the words in the same group. To do that, we need to keep track of the current word, the sum of the durations of the current group, and the count of the words in the current group.
4. If the current word is the same as the previous word, we add the duration to the sum, and increment the count by 1.
5. If the current word is not the same as the previous word, we append the sum multiplied by the count to the output list, and reset the current word, the sum, and the count.
6. After we finish looping through all the rows in the dataframe, we need to add the sum multiplied by the count for the last word to the output list.


`by_sentence_count`

1. We split the list into sublists whenever 'SP' is encountered
2. We iterate over each sublist and calculate the length of the sublist
3. We add the length of each sublist to the result list the number of times equal to the length of the sublist
4. We append 'SP' after each complete sentence except the last one
5. We return two lists: a list of phoneme counts and a list of syllable counts for each sentence.

In [23]:
def SentenceDuration(df):
    sentence_unique_durations= []
    sentence_duration = 0
    counter = 0
    for index, (i, j) in enumerate(zip(df['Duration (ms.)'].tolist(), df['Word'].tolist())):
        if j == 'SP' and counter > 0:
            sentence_unique_durations.append([sentence_duration] * counter)
            # Avoid adding the last 'SP'
            if index != len(df['Word']) - 1:
                sentence_unique_durations.append(j)
            sentence_duration = 0
            counter = 0
        else:
            sentence_duration += float(i)
            counter += 1
    # Handle the case where there's no 'SP' at the end
    if counter > 0:
        sentence_unique_durations.extend([sentence_duration] * counter)

    return collapse_nested_list(sentence_unique_durations)



def by_sentence_count(syllable_indices, excluded_indices):
    # Split the list into sublists whenever 'SP' is encountered, keeping track of original indices
    splits = []
    current_split = []
    original_indices = []  # To keep track of original indices
    current_original_indices = []

    for idx, original_idx in enumerate(syllable_indices):
        if original_idx == 'SP':
            if current_split:
                splits.append(current_split)
                original_indices.append(current_original_indices)
            current_split = []
            current_original_indices = []
        else:
            current_split.append(original_idx)
            current_original_indices.append(idx)  # Store the original index

    # Add the last split if 'SP' wasn't the last element
    if current_split:
        splits.append(current_split)
        original_indices.append(current_original_indices)

    # Initialize result lists
    sentence_length_by_phoneme_repeated = []
    sentence_length_by_syllable_repeated = []

    # Process all splits
    for split, orig_idxs in zip(splits, original_indices):
        phoneme_length = len(split)
        syllable_length = len(set(idx for idx in split if idx != 'OP'))

        op_count = split.count('OP')
        syllable_length += op_count

        # Calculate the count of double consonants within this split using original indices
        double_consonant_count = sum(1 for orig_idx in orig_idxs if orig_idx in double_consonant_indices)

        adjusted_phoneme_count = phoneme_length - op_count - double_consonant_count

        # Extend by adjusted phoneme and syllable counts
        sentence_length_by_phoneme_repeated.extend([adjusted_phoneme_count] * phoneme_length)
        sentence_length_by_syllable_repeated.extend([syllable_length - op_count] * phoneme_length)

        if split is not splits[-1]:
            sentence_length_by_phoneme_repeated.append('SP')
            sentence_length_by_syllable_repeated.append('SP')

    return sentence_length_by_phoneme_repeated, sentence_length_by_syllable_repeated

In [24]:
sentence_durations = SentenceDuration(df)
sentence_length_by_phoneme, sentence_length_by_syllable = by_sentence_count(unique_syll_idx,double_consonant_indices)
#keep
df['SentenceDuration'] = sentence_durations
df['SentenceLengthByPhoneme'] = sentence_length_by_phoneme
df['SentenceLengthBySyllable'] = sentence_length_by_syllable

### SegmentType Column
*   use `char_only()` to remove diacritics and special symbols and `segment_type` to get the type of character.
* We can use the original phoneme list

In [25]:
def segment_type(list):
    segment_type_list = []
    for segment in list:
        if segment == 'OP' or segment == 'SP':
            segment_type_list.append(segment)
        else:
            temp = IPAString(segment,geminate=GEMINATE).char_only()
            type = IPAString(temp).segment_type
            segment_type_list.append(type)

    temp = collapse_nested_list(segment_type_list)
    segment_type_column = ['C' if item == 'CONSONANT' else 'V' if item == 'VOWEL' else item for item in temp]
    return segment_type_column

In [26]:
original_phonemes_list = df['Phoneme'].tolist()

segment_type_column = segment_type(original_phonemes_list)
print('segment_type_column',len(segment_type_column))
df['SegmentType'] = segment_type_column

segment_type_column 398

In [27]:
###############
data = {
    'Original Word Column': df['Word'],
    'Repeated Word List': repeated_word_list,
    'Word Labels': word_labels,
    'Unique Word Index': unique_word_idx,
    'Phoneme': df['Phoneme'],
    'wlbp': wlbp,
    'wlbs': wlbs,
    'segment_type': segment_type_column
}

# Converting the dictionary into a DataFrame
test_df = pd.DataFrame({k: pd.Series(v) for k, v in data.items()})



test_df.to_excel("check.xlsx")

### CodaComplexity Column

*   Use `.coda` from `IPAString` on temporary syllables column to return coda for each syllable

In [28]:
def coda_column(repeated_syllable_list):
    coda_list = []
    for syllable in repeated_syllable_list:
        if syllable == 'OP' or syllable == 'SP':
            coda_list.append(syllable)
        else:
         coda_list.append(IPAString(syllable,geminate=GEMINATE).coda)
    return coda_list

In [29]:
coda_column = coda_column(repeated_syllable_list)
print('coda_column',len(coda_column))

#fix this to actually count the coda
df['CodaComplexity'] = coda_column

coda_column 398

### Stress Column


*   Use `.stress()` from `IPAString` on syllable column to return type of stress. (primary/secondary/unstressed)

In [30]:
def stress_column(repeated_syllable_list):
    stress_list = []
    for syllable in repeated_syllable_list:
        if syllable == 'OP' or syllable == 'SP':
            stress_list.append(syllable)
        else:
            stress_list.append(IPAString(syllable).stress())

    return stress_list

In [31]:
stress_column = stress_column(repeated_syllable_list)
print('stress_column',len(stress_column))

df['Stress'] = stress_column

stress_column 398

###Interstress Intervals

`create_isi_blocks`
1. Iterate through each row in the DataFrame, starting from the second row.
2. Check if the current syllable is stressed. If so, set the encountered_stressed_syllable to True.
3. Check if the current syllable is stressed and there was a change in unique_syll_idx.
   Only do this if we have previously encountered a stressed syllable.
4. If the above condition is met, set the new_block column to True.
5. Reset the block if 'SP' is detected with duration 0 and set the next syllable to start a new block if it's stressed.
6. Set the first entry to start a new block only if it's stressed.

`get_isi_index`

*   gets the index location of every interstress interval start

`calculate_interstress_duration(df, isi_idx, summed_col_name='', excluded_words=None)`

* Gets the duration of the ISI block. 'summed_col_name is' the parameter for whichever column you are creating. If you need ISI with pause or without. For without you have an additional parameter excluded_words which is used for OP/SP.


`ISI_Pause` checks for a difference between pause columns (a difference would imply a pause) it then further checks if the pause occurs within an SP and then labels them accordingly

`ISI_By_Segment` and `ISI_By_Syllable` uses similar logic as before to get the repeated values. By_Segment returns 3 values, segment (C+V), consonant, vowel

In [32]:
# Function to update the 'new_block' column
def create_isi_blocks(df):
    df['new_block'] = False
    # Initialize a variable to track the occurrence of a stressed syllable
    encountered_stressed_syllable = False

    # Iterate through the DataFrame starting from the second row
    for i in range(1, len(df)):
        curr_stress = df.at[i, 'Stress']
        prev_syll_idx = df.at[i-1, 'unique_syll_idx']
        curr_syll_idx = df.at[i, 'unique_syll_idx']
        curr_duration = df.at[i, 'Duration (ms.)']

        # If the current syllable is stressed, set the encountered_stressed_syllable to True
        if curr_stress in ['STRESSED', 'STRESSED_2']:
            encountered_stressed_syllable = True

        # Start a new block if the current syllable is stressed and there was a change in unique_syll_idx
        # Only do this if we have previously encountered a stressed syllable
        if encountered_stressed_syllable and \
           ((curr_stress in ['STRESSED', 'STRESSED_2']) and curr_syll_idx != prev_syll_idx):
            df.at[i, 'new_block'] = True
        # Reset the block if 'SP' is detected with duration 0
        # and set the next syllable to start a new block if it's stressed
        elif curr_syll_idx == 'SP' and curr_duration == 0:
            encountered_stressed_syllable = False  # Reset encountered_stressed_syllable
            if (i+1 < len(df)) and (df.at[i+1, 'Stress'] in ['STRESSED', 'STRESSED_2']):
                df.at[i+1, 'new_block'] = True
        else:
            df.at[i, 'new_block'] = False

    # Set the first entry to start a new block only if it's stressed
    df.at[0, 'new_block'] = df.at[0, 'Stress'] in ['STRESSED', 'STRESSED_2']

    return df



# Call the function to set new blocks
def get_isi_idx(df):
    df = create_isi_blocks(df)
    isi_idx = df.index[df['new_block']].tolist()
    isi_idx.append(len(df))
    return isi_idx


def calculate_interstress_duration(df, isi_idx, summed_col_name='', excluded_words=None):
    # Initialize the new column for summed durations with the syllable's own duration
    df[summed_col_name] = df['SyllableDuration']

    # Loop to calculate the sum durations for each range
    for start, end in zip(isi_idx, isi_idx[1:] + [None]):
        # If 'end' is None, it means we reached the last index, so include the last item
        range_end = end or len(df)

        # Select the slice of the DataFrame we're interested in
        df_slice = df[start:range_end]

        # Perform the sum, either excluding specific words or not
        if excluded_words:
            sum_duration = df_slice[~df_slice['Word'].isin(excluded_words)]['Duration (ms.)'].sum()
        else:
            sum_duration = df_slice['Duration (ms.)'].sum()

        # Assign the sum to the new column in the appropriate slice
        df.loc[start:range_end - 1, summed_col_name] = sum_duration

    # Return the modified DataFrame
    return df


def ISI_Pause(df, isi_idx):
    # Initialize a new column with 'No' indicating no difference
    df['ISIPause'] = 'No'

    # Loop to check for differences in each block range
    for start, end in zip(isi_idx, isi_idx[1:] + [None]):
        # Define the range end
        range_end = end if end is not None else len(df)

        # Get the slice of the DataFrame we're interested in
        df_slice = df.iloc[start:range_end]

        # Check for differences in the slice
        difference = df_slice['InterStressDuration'] != df_slice['ISIDurationNoPause']

        # If there's a difference, we'll mark it accordingly
        if difference.any():
            if 'SP' in df_slice['syllables'].values:
                df.loc[start:range_end-1, 'ISIPause'] = 'yes(SP)'
            else:
                df.loc[start:range_end-1, 'ISIPause'] = 'yes'
        # If there's no difference, it will remain 'No'

    return df



def ISI_By_Segment(df, isi_idx, excluded_indices, segment_col='SegmentType'):
    isi_idx.insert(0, 0)
    # Initialize lists to hold the final repeated segment counts
    ISI_consonant_count = []
    ISI_vowel_count = []

    # Loop over each interval
    for start, end in zip(isi_idx, isi_idx[1:] + [None]):
        # Define the range end (non-inclusive)
        range_end = end if end is not None else len(df)

        # Get the slice of the DataFrame we're interested in
        df_slice = df.iloc[start:range_end]

        # Count the occurrences of consonants and vowels, ignoring 'SP' and 'OP'
        consonant_count = (df_slice[segment_col] == 'C').sum()
        vowel_count = (df_slice[segment_col] == 'V').sum()

        # Exclude specific indices if they fall within this slice
        excluded_count = sum(1 for idx in range(start, range_end) if idx in excluded_indices)

        # Adjust the consonant and vowel counts
        adjusted_consonant_count = consonant_count - excluded_count
        adjusted_vowel_count = vowel_count

        # Calculate the length of the interval including 'OP' and 'SP'
        interval_length = range_end - start

        # Repeat the adjusted counts for the length of the interval
        ISI_consonant_count.extend([adjusted_consonant_count] * interval_length)
        ISI_vowel_count.extend([adjusted_vowel_count] * interval_length)

        ISI_segment_count = [x + y for x, y in zip(ISI_consonant_count, ISI_vowel_count)]

    return ISI_segment_count, ISI_consonant_count, ISI_vowel_count



def ISI_By_Syllable(df, intervals, unique_syll_col='unique_syll_idx', word_column='Word'):
    isi_idx.insert(0, 0)
    # This list will hold the final repeated syllable counts
    repeated_syllable_counts = []

    # Loop over each interval
    for start, end in zip(intervals, intervals[1:] + [None]):
        # Define the range end (non-inclusive)
        range_end = end if end is not None else len(df)

        # Get the slice of the DataFrame we're interested in
        df_slice = df.iloc[start:range_end]

        # Determine the set of unique syllable indices, excluding 'SP' and 'OP'
        unique_syllables = set(df_slice[~df_slice[word_column].isin(['SP', 'OP'])][unique_syll_col])

        # Calculate the length of the unique syllables
        unique_syllable_count = len(unique_syllables)

        # Repeat this count for the length of the interval
        repeated_syllable_counts.extend([unique_syllable_count] * (range_end - start))

    return repeated_syllable_counts

In [33]:
df

,Filename,Sentence,Word,Phoneme,Begin,End,Duration (ms.),WordLengthByPhoneme,WordLengthBySyllable,WordNumber,...,syllables,unique_syll_idx,SyllableLengthByPhoneme,SyllableDuration,SentenceDuration,SentenceLengthByPhoneme,SentenceLengthBySyllable,SegmentType,CodaComplexity,Stress
0,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,ʔ,0.08876,0.12333,34.57,9,4,1,...,ʔa,1,2,179.26,2250.07,14,6,C,0,UNSTRESSED
1,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,a,0.12333,0.26802,144.69,9,4,1,...,ʔa,1,2,179.26,2250.07,14,6,V,0,UNSTRESSED
2,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,t,0.26802,0.45239,184.38,9,4,1,...,tja,2,3,373.44,2250.07,14,6,C,0,UNSTRESSED
3,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,j,0.45239,0.50462,52.23,9,4,1,...,tja,2,3,373.44,2250.07,14,6,C,0,UNSTRESSED
4,01-Cold_Wind_and_Sun-1_of_9,S1,ʔa.tja.ˈjaː.ja,a,0.50462,0.64145,136.83,9,4,1,...,tja,2,3,373.44,2250.07,14,6,V,0,UNSTRESSED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,09-Cold_Wind_and_Sun-9_of_9,S9,ˈχtut.χaw,u,6.36828,6.47982,111.54,7,2,9,...,ˈχtut,164,4,490.88,6201.54,49,19,V,1,STRESSED
394,09-Cold_Wind_and_Sun-9_of_9,S9,ˈχtut.χaw,t,6.47982,6.55789,78.07,7,2,9,...,ˈχtut,164,4,490.88,6201.54,49,19,C,1,STRESSED
395,09-Cold_Wind_and_Sun-9_of_9,S9,ˈχtut.χaw,χ,6.55789,6.70504,147.15,7,2,9,...,χaw,165,3,372.40,6201.54,49,19,C,1,UNSTRESSED
396,09-Cold_Wind_and_Sun-9_of_9,S9,ˈχtut.χaw,a,6.70504,6.80879,103.76,7,2,9,...,χaw,165,3,372.40,6201.54,49,19,V,1,UNSTRESSED
397,09-Cold_Wind_and_Sun-9_of_9,S9,ˈχtut.χaw,w,6.80879,6.93028,121.49,7,2,9,...,χaw,165,3,372.40,6201.54,49,19,C,1,UNSTRESSED

In [34]:
isi_idx = get_isi_idx(df)
df = calculate_interstress_duration(df, isi_idx, 'InterStressDuration', excluded_words=None)
df = calculate_interstress_duration(df, isi_idx, 'ISIDurationNoPause', excluded_words={'OP', 'SP'})
df = ISI_Pause(df, isi_idx)

# Assuming df is your DataFrame and 'SegmentType' identifies segment types
by_segment, by_consonant, by_vowel = ISI_By_Segment(df, isi_idx,double_consonant_indices)
ISIBySyllable = ISI_By_Syllable(df, isi_idx)
print('by_segment',len(by_segment))
print('by_consonant',len(by_consonant))
print('by_vowel',len(by_vowel))
print('by_syllable',len(ISIBySyllable))

df['ISIBySyllable'] = ISIBySyllable
df['ISIBySegment'] = by_segment
df['ISIByConsonant'] = by_consonant
df['ISIByVowel'] = by_vowel

by_segment 398
by_consonant 398
by_vowel 398
by_syllable 398

`fill_pause_columns` creates OtherPauses & SentencePauses columns.

`remove_pause_rows` just removes those rows for final sheet.

`update_isi_columns` sets all columns that concern ISI to 'N/A' when there is no stress encountered whatsoever.

The rest is just finalizing the sheet how Ryan requires it.

In [35]:
def fill_pause_columns(df):
    df['OtherPauses'] = np.nan
    df['SentencePauses'] = np.nan
    last_op_duration = np.nan
    last_sp_duration = np.nan
    for i in range(len(df) - 1, -1, -1):
        word = df.at[i, 'Word']
        duration = df.at[i, 'Duration (ms.)']
        if word == 'OP':
            last_op_duration = duration
        elif word == 'SP':
            last_sp_duration = duration if duration > 0 else np.nan
            last_op_duration = np.nan
        if pd.notna(last_op_duration):
            df.at[i, 'OtherPauses'] = last_op_duration
        if pd.notna(last_sp_duration):
            df.at[i, 'SentencePauses'] = last_sp_duration
    df.loc[df['Word'] == 'SP', 'SentencePauses'] = df.loc[df['Word'] == 'SP', 'Duration (ms.)'].where(
        df.loc[df['Word'] == 'SP', 'Duration (ms.)'] > 0, np.nan
    )
    return df


def remove_pause_rows(df):
    # Get indices of rows with 'OP' or 'SP'
    op_sp_indices = df.index[df['Word'].isin(['OP', 'SP'])].tolist()

    # Drop rows with 'OP' or 'SP'
    df_cleaned = df.drop(op_sp_indices).reset_index(drop=True)

    return df_cleaned

def update_isi_columns(df):
    # Check if all values in 'STRESS' column are unstressed
    if df['Stress'].eq('UNSTRESSED').all():
        df['InterStressDuration'] == 'N/A'
        # Iterate over all columns
        for col in df.columns:
            # Check if 'ISI' is in the column name
            if 'ISI' in col:
                # Set the entire column to 'N/A'
                df[col] = 'N/A'
    return df

In [36]:
print("OP:", (df['Word'] == 'OP').sum(), "SP:", (df['Word'] == 'SP').sum())
print(df[['Word','Duration (ms.)']].head(20))

OP: 1 SP: 8
                       Word  Duration (ms.)
0            ʔa.tja.ˈjaː.ja           34.57
1            ʔa.tja.ˈjaː.ja          144.69
2            ʔa.tja.ˈjaː.ja          184.38
3            ʔa.tja.ˈjaː.ja           52.23
4            ʔa.tja.ˈjaː.ja          136.83
5            ʔa.tja.ˈjaː.ja          101.41
6            ʔa.tja.ˈjaː.ja          249.84
7            ʔa.tja.ˈjaː.ja          107.24
8            ʔa.tja.ˈjaː.ja          176.65
9                  ˈʔaː.nin          106.52
10                 ˈʔaː.nin          287.68
11                 ˈʔaː.nin          113.61
12                 ˈʔaː.nin          266.75
13                 ˈʔaː.nin          287.67
14                       SP            0.00
15  pa.pa.ta.na.ˈwiːχ.ʃa.na           26.33
16  pa.pa.ta.na.ˈwiːχ.ʃa.na          104.43
17  pa.pa.ta.na.ˈwiːχ.ʃa.na           61.97
18  pa.pa.ta.na.ˈwiːχ.ʃa.na          111.44
19  pa.pa.ta.na.ˈwiːχ.ʃa.na           98.18

In [37]:
df = fill_pause_columns(df)
df = remove_pause_rows(df)
df = update_isi_columns(df)
df['WordNumber']  = ['W' + str(i) for i in df['WordNumber']]
df['SyllableNumber']  = ['SYLL' + str(i) for i in df['SyllableNumber']]


final_df = df[['Filename','Sentence','WordNumber','Word','SyllableNumber','Phoneme','SegmentType','CodaComplexity','Stress','SyllableLengthByPhoneme','WordLengthByPhoneme',
               'SentenceLengthByPhoneme','SentenceLengthBySyllable','WordLengthBySyllable',	'Begin','End',	'Duration (ms.)','SyllableDuration','WordDuration',
               'SentenceDuration',	'InterStressDuration'	,'ISIDurationNoPause',	'ISIPause',	'ISIBySegment',	'ISIBySyllable',	'ISIByConsonant',	'ISIByVowel',	'OtherPauses',	'SentencePauses']]

final_df

,Filename,Sentence,WordNumber,Word,SyllableNumber,Phoneme,SegmentType,CodaComplexity,Stress,SyllableLengthByPhoneme,...,SentenceDuration,InterStressDuration,ISIDurationNoPause,ISIPause,ISIBySegment,ISIBySyllable,ISIByConsonant,ISIByVowel,OtherPauses,SentencePauses
0,01-Cold_Wind_and_Sun-1_of_9,S1,W1,ʔa.tja.ˈjaː.ja,SYLL1,ʔ,C,0,UNSTRESSED,2,...,2250.07,179.26,179.26,No,5,2,3,2,NaN,NaN
1,01-Cold_Wind_and_Sun-1_of_9,S1,W1,ʔa.tja.ˈjaː.ja,SYLL1,a,V,0,UNSTRESSED,2,...,2250.07,179.26,179.26,No,5,2,3,2,NaN,NaN
2,01-Cold_Wind_and_Sun-1_of_9,S1,W1,ʔa.tja.ˈjaː.ja,SYLL2,t,C,0,UNSTRESSED,3,...,2250.07,373.44,373.44,No,5,2,3,2,NaN,NaN
3,01-Cold_Wind_and_Sun-1_of_9,S1,W1,ʔa.tja.ˈjaː.ja,SYLL2,j,C,0,UNSTRESSED,3,...,2250.07,373.44,373.44,No,5,2,3,2,NaN,NaN
4,01-Cold_Wind_and_Sun-1_of_9,S1,W1,ʔa.tja.ˈjaː.ja,SYLL2,a,V,0,UNSTRESSED,3,...,2250.07,373.44,373.44,No,5,2,3,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,09-Cold_Wind_and_Sun-9_of_9,S9,W9,ˈχtut.χaw,SYLL1,u,V,1,STRESSED,4,...,6201.54,863.28,863.28,No,7,2,5,2,NaN,NaN
385,09-Cold_Wind_and_Sun-9_of_9,S9,W9,ˈχtut.χaw,SYLL1,t,C,1,STRESSED,4,...,6201.54,863.28,863.28,No,7,2,5,2,NaN,NaN
386,09-Cold_Wind_and_Sun-9_of_9,S9,W9,ˈχtut.χaw,SYLL2,χ,C,1,UNSTRESSED,3,...,6201.54,863.28,863.28,No,7,2,5,2,NaN,NaN
387,09-Cold_Wind_and_Sun-9_of_9,S9,W9,ˈχtut.χaw,SYLL2,a,V,1,UNSTRESSED,3,...,6201.54,863.28,863.28,No,7,2,5,2,NaN,NaN
388,09-Cold_Wind_and_Sun-9_of_9,S9,W9,ˈχtut.χaw,SYLL2,w,C,1,UNSTRESSED,3,...,6201.54,863.28,863.28,No,7,2,5,2,NaN,NaN

Let output.xlsx load into folder menu.

In [38]:
final_df.to_excel("/Users/yanlashchev/Desktop/IPA_Project/IPA_parser/output.xlsx", index=False, na_rep="N/A")

# FIN